networks:
  simple-app-net:
    driver: bridge

services:
  simple-app:
    image: uvadm/simple-app:tag
    container_name: simple-app-container
    hostname: simple-app
    user: appuser
    ports:
      - "5000:5000"
    networks:
      - simple-app-net